"""add document understanding fields

Revision ID: 1fccab4b892a
Revises: 958c176ebca6
Create Date: 2026-05-16 22:07:08.519505
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fccab4b892a'
down_revision = '958c176ebca6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('journey_candidate', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('suggested_next_step', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'suggested_next_step')
    op.drop_column('documents', 'summary')
    op.drop_column('documents', 'journey_candidate')
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
