"""add workflow states

Revision ID: 60763db53b78
Revises: 13dbc22f37bd
Create Date: 2026-05-16 10:59:28.270460
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60763db53b78'
down_revision = '13dbc22f37bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_type', sa.String(length=64), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_states_conversation_id'), 'workflow_states', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_workflow_states_user_id'), 'workflow_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_states_user_id'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_conversation_id'), table_name='workflow_states')
    op.drop_table('workflow_states')
    # ### end Alembic commands ###
