"""add extracted text to documents

Revision ID: 958c176ebca6
Revises: 91f50923efae
Create Date: 2026-05-16 17:58:03.643491
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958c176ebca6'
down_revision = '91f50923efae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
